### ISSUE TITLE
Installation: can't find in MELPA

### ISSUE THREAD

**Issue by aaaxx** [lueck/standoff-mode#2]
I'm a total noob at Emacs, so I'm sorry if I'm missing something obvious.

I've added the package-archives line to the init file, but all I get is `[No match]` when I type `M-x package-install RET standoff-mode`

**Comment by lueck** [comment]
Hi,
thanks for making that point! The installation instructions in `README` were incomplete. Please run
`M-x package-refresh-contents RET`
to make the packages from melpa 'available' before
`M-x package-install RET standoff-mode RET`

Alternatively you can call the package installation menu, which fetches a list of available package first:
`M-x package-list-packages RET`

I fixed the installation instructions.

Thanks
Christian

**Comment by aaaxx** [comment]
Hmm, still getting `[No match]`. It's also not in the package list.

**Comment by lueck** [comment]
Are there packages from melpa in the list of available packages? The fourth column in the package menu (`M-x package-list-packages RET`) says, from which archive a package is from. For example, is `0xc` from melpa available?

**Comment by aaaxx** [comment]
No, it's listing only gnu packages.

**Comment by aaaxx** [comment]
Ah, found the cause. According to MELPA's [Getting started page](https://melpa.org/#/getting-started):

>  **Note:** There are some problems using the `https` location with Emacs on Windows. There is currently no know easy fix for this. You can still use MELPA by using the non-SSL location by replacing `https` with `http`.

Works fine now with http.

**Comment by lueck** [comment]
Good. I also added this to the installation instructions.
